ludus:
  - vm_name: "{{ range_id }}-ad-win11-22h2-enterprise-x64-1"
    hostname: "{{ range_id }}-WIN11-ADSA"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 21
    ram_gb: 82
    cpus: 18
    windows:
      chocolatey_packages:
        - vscodium
        - googlechrome
      chocolatey_ignore_checksums: true # Chrome updates faster than choco package hash updates
      office_version: 2021
      office_arch: 64bit
    roles:
      - local-bloodhound
